CREATE TABLE ACME_ACCOUNT_NEW
(
    ID           INTEGER PRIMARY KEY AUTOINCREMENT,
    EMAIL        TEXT NOT NULL,
    PRIVATE_KEY  BLOB NOT NULL,
    REGISTRATION TEXT NOT NULL DEFAULT '',
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ACME_ACCOUNT_NEW SELECT * FROM ACME_ACCOUNT;

DROP TABLE ACME_ACCOUNT;
ALTER TABLE ACME_ACCOUNT_NEW RENAME TO ACME_ACCOUNT;


ALTER TABLE ACME_CERTIFICATE ADD COLUMN ACME_ACCOUNT_ID INTEGER;

UPDATE ACME_CERTIFICATE SET ACME_ACCOUNT_ID = (SELECT ID FROM ACME_ACCOUNT LIMIT 1);



CREATE UNIQUE INDEX IF NOT EXISTS idx_acme_account_email ON ACME_ACCOUNT (EMAIL);


ALTER TABLE ACME_CONFIGURATION ADD COLUMN AUTO_DISCOVER BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE ACME_CONFIGURATION SET AUTO_DISCOVER = TRUE WHERE ACME_DOMAINS = '' OR ACME_DOMAINS IS NULL;
